#' Generate operating characteristics for multiple simulations
#' 
#' Obtain the operating characteristics of the CFO-type designs for multiple simulations.
#'
#' @usage CFO.oc(nsimu=5000, design, target, p.true, ncohort, init.level, cohortsize,
#'        tau=NA, accrual=NA, tite.dist=NA, accrual.dist=NA, 
#'        prior.para=list(alp.prior=target, bet.prior=1-target), seeds = NULL,
#'        cutoff.eli=0.95, extrasafe=FALSE, offset=0.05)
#'
#' @param nsimu the total number of trials to be simulated. The default value is 5000.
#' @param design option for selecting different designs, which can be set as \code{'CFO'}, \code{'aCFO'},
#'               \code{'TITE-CFO'}, \code{'TITE-aCFO'}, \code{'fCFO'}, \code{'f-aCFO'}, \code{'bCFO'}, 
#'               and \code{'b-aCFO'}. Specifically, \code{'bCFO'} refers to the benchmark CFO, and 
#'               \code{'b-aCFO'} denotes the benchmark aCFO.
#' @param target the target DLT rate.
#' @param p.true the true DLT rates under the different dose levels.
#' @param ncohort the total number of cohorts.
#' @param init.level the dose level assigned to the first cohort. The default value \code{init.level} is 1.
#' @param cohortsize the number of patients or size of each cohort. The default value \code{cohortsize} is 3. 
#' @param tau maximal assessment window size. 'NA' should be assigned if the design without late-oneset outcomes.
#' @param accrual the accrual rate, i.e., the number of patients accrued in tau time. 'NA' should be assigned 
#'                if the design without late-oneset outcomes.
#' @param tite.dist the distribution of the time to DLT events. \code{tite.dist=1} corresponds to a uniform distribution, 
#'                  \code{tite.dist=2} corresponds to a Weibull distribution, and \code{tite.dist=3} corresponds to a 
#'                  log-logistic distribution. 'NA' should be assigned if the design without late-oneset outcomes.
#' @param accrual.dist the distribution of the arrival times of patients. When \code{tite.dist=1}, it corresponds to all 
#'                     patients in each cohort arriving simultaneously at a given accrual rate. When \code{tite.dist=2}, 
#'                     it corresponds to a uniform distribution, and when \code{tite.dist=3}, it corresponds to an 
#'                     exponential distribution. 'NA' should be assigned if the design without late-oneset outcomes.
#' @param prior.para the prior parameters for a beta distribution, usually set as list(alp.prior=target, bet.prior=1-target) by default. \code{alp.prior} 
#'                 and \code{bet.prior} represent the parameters of the prior distribution for the true DLT rate at 
#'                 any dose level. This prior distribution is specified as Beta( \code{alpha.prior}, \code{beta.prior}).
#' @param cutoff.eli the cutoff to eliminate overly toxic doses for safety. We recommend
#'                    the default value of (\code{cutoff.eli=0.95}) for general use.
#' @param extrasafe set \code{extrasafe=TRUE} to impose a more strict early stopping rule for
#'                   extra safety
#' @param offset a small positive number (between \code{0} and \code{0.5}) to control how strict the
#'                stopping rule is when \code{extrasafe=TRUE}. A larger value leads to
#'                a more strict stopping rule. The default value \code{offset=0.05}
#'                generally works well.
#' @param seeds A vector of random seeds for each simulation, for example, \code{seeds = 1:nsimu} (default is NULL).
#'
#' @details The operating characteristics of CFO-type and aCFO-type designs are generated by simulating trials under the 
#'          pre-specified true toxicity probabilities of the investigational doses. The choice of which design to execute 
#'          is determined by setting the \code{design} parameter. Some parameters (\code{tau}, \code{accrual}, 
#'          \code{tite.dist}, and \code{accrual.dist}) need to be set only when running a design that can handle late-onset 
#'          toxicities; otherwise, they default to NA.\cr
#'          Additionally, in the example, we set \code{nsimu=100} for testing time considerations. In reality, \code{nsimu} 
#'          is typically set to 5000 to ensure the accuracy of the results.
#'
#' @return the \code{ CFO.oc() } function returns basic setup of ($simu.setup and $p.true) and the operating 
#'         characteristics ($selPercent,$dose.ns,$DLT.ns and $simu.oc) of the design. \cr
#'         The operating characteristics includes \cr
#'         (1) selection percentage at each dose level ($selPercent) \cr
#'         (2) averaged number of toxicity observed at each dose level in one simulation ($DLT.ns) \cr
#'         (3) averaged number of patients treated at each dose level in one simulation ($dose.ns) \cr
#'         (4) percentage of correct selection of the MTD ($simu.oc$MTDSel) \cr
#'         (5) percentage of patients allocated to the MTD ($simu.oc$MTDAllo) \cr
#'         (6) percentage of selecting a dose above the MTD ($simu.oc$overSel) \cr
#'         (7) percentage of allocating patients at dose levels above the MTD ($simu.oc$overAllo) \cr
#'         (8) percentage of the patients suffering DLT ($simu.oc$averDLT) \cr
#'         (9) average trial duration if trials with late-onset toxicities ($simu.oc$averDur) \cr
#'         (10) number of simulations terminated due to early stopping ($simu.oc$errStop) \cr
#'         (11) number of patients entering the trial ($simu.oc$tol.Subjs)
#' @importFrom dplyr transmute
#' @export
#'
#' @examples
#' ## setting
#' nsimu <- 100; target <- 0.2; ncohort <- 12; cohortsize <- 3; init.level <- 1
#' p.true <-c(0.01, 0.05, 0.10, 0.14, 0.20, 0.26, 0.34)
#' prior.para=list(alp.prior=target, bet.prior=1-target)
#' tau <- 3; accrual <- 6; tite.dist <- 2; accrual.dist <- 2
#' 
#' ## get the operating characteristics for 100 simulations using the CFO design
#' CFOoc <- CFO.oc (nsimu, design='CFO', target, p.true, ncohort, init.level, cohortsize,
#'          tau=NA, accrual=NA, tite.dist=NA, accrual.dist=NA, prior.para, seeds = 1:nsimu)
#' summary(CFOoc)
#' plot(CFOoc)
#' ## get the operating characteristics for 100 simulations using the aCFO design
#' aCFOoc <- CFO.oc (nsimu, design='aCFO', target, p.true, ncohort, init.level, cohortsize,
#'        tau=NA, accrual=NA, tite.dist=NA, accrual.dist=NA, prior.para, seeds = 1:nsimu)
#' summary(aCFOoc)
#' plot(aCFOoc)
#' ## get the operating characteristics for 100 simulations using the TITE-CFO design
#' TITECFOoc <- CFO.oc (nsimu, design='TITE-CFO', target, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, prior.para, seeds = 1:nsimu)
#' summary(TITECFOoc)
#' plot(CFOoc)
#' ## get the operating characteristics for 100 simulations using the TITE-aCFO design
#' TITEaCFOoc <- CFO.oc (nsimu, design='TITE-aCFO', target, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, prior.para)
#' summary(TITEaCFOoc)
#' plot(TITEaCFOoc)
#' ## get the operating characteristics for 100 simulations using the fCFO design
#' fCFOoc <- CFO.oc (nsimu, design='fCFO', target, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, prior.para, seeds = 1:nsimu)
#' summary(fCFOoc)
#' plot(fCFOoc)
#' ## get the operating characteristics for 100 simulations using the f-aCFO design
#' faCFOoc <- CFO.oc (nsimu, design='f-aCFO', target, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, prior.para, seeds = 1:nsimu)
#' summary(faCFOoc)
#' plot(faCFOoc)
#' ## get the operating characteristics for 100 simulations using the bCFO design
#' bCFOoc <- CFO.oc (nsimu, design='bCFO', target, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, prior.para, seeds = 1:nsimu)
#' summary(bCFOoc)
#' plot(bCFOoc)
#' ## get the operating characteristics for 100 simulations using the b-aCFO design
#' baCFOoc <- CFO.oc (nsimu, design='b-aCFO', target, p.true, ncohort, init.level, cohortsize,
#'         tau, accrual, tite.dist, accrual.dist, prior.para, seeds = 1:nsimu)
#' summary(baCFOoc)
#' plot(baCFOoc)
CFO.oc <- function(nsimu=5000, design, target, p.true, ncohort, init.level, cohortsize,
                   tau=NA, accrual=NA, tite.dist=NA, accrual.dist=NA, 
                   prior.para=list(alp.prior=target, bet.prior=1-target), seeds = NULL,
                   cutoff.eli=0.95, extrasafe=FALSE, offset=0.05){
  ###############################################################################
  ###############define the functions used for main function#####################
  ###############################################################################
  post.process.onemethod <- function(res, paras){
    tmtd <- paras$mtd
    target <- paras$target
    ndose <- length(paras$p.true)
    rv <- rep(0, 7)
    rv[1] <- sum(res$MTD==tmtd)
    rv[2] <- res$dose.ns[tmtd]
    if (res$MTD == 99){
      rv[3] <- 0
    }else{
      rv[3] <- sum(res$MTD>tmtd)
    }
    if (tmtd==ndose){
      rv[4] <- 0
    }else{
      rv[4] <- sum(res$dose.ns[(tmtd+1):ndose])
    }
    rv[5] <- sum((sum(res$DLT.ns)/sum(res$dose.ns))>target)
    rv[6] <- sum(res$DLT.ns)
    rv[7] <- sum(res$dose.ns)
    if (!is.null(res$total.time)){
      rv <- c(rv, res$total.time)
      names(rv) <- c(
        "MTD Sel", "MTD Allo", "Over Sel", 
        "Over Allo", "Risk of HT", "No DLT",
        "No Subject", "Duration")
    }else{
      names(rv) <- c(
        "MTD Sel", "MTD Allo", "Over Sel", 
        "Over Allo", "Risk of HT", "No DLT",
        "No Subject")
    }
    rv
    
  }
  
  post.process.single <- function(result){
    nMethod <- length(result)-1
    paras <- result$paras
    tmtd <- paras$mtd
    methods <- names(result)[1:nMethod]
    res.v <- list()
    for (name in methods){
      res.v[[name]] <- post.process.onemethod(result[[name]], paras)
    }
    do.call(rbind, res.v)
  }
  
  MTD.level <- function(phi, p.true){
    if (p.true[1]>phi+0.1){
      MTD <- 99
      return(MTD)
    }
    MTD <- which.min(abs(phi - p.true))
    return(MTD)
  }
  
  post.process <- function(results){
    MTD.Sel <- 0; MTD.Allo <- 0; Over.Sel <-0; Over.Allo <-0
    Risk.of.HT<-0; No.DLT<-0; Duration<-0; No.Subject<-0
    nsimu <- length(results)
    res.all <- 0
    for (result in results){
      res.all <- post.process.single(result) + res.all
    }
    res.all.df <- data.frame(res.all)
    if (is.null(res.all.df$Duration)){
      final.res <- dplyr::transmute(res.all.df, 
                                    MTD.Sel=MTD.Sel/nsimu,
                                    MTD.Allo=MTD.Allo/No.Subject,
                                    Over.Sel=Over.Sel/nsimu,
                                    Over.Allo=Over.Allo/No.Subject,
                                    Risk.of.HT=Risk.of.HT/nsimu,
                                    PerDLT=No.DLT/No.Subject
      )
    }else{
      final.res <- dplyr::transmute(res.all.df, 
                                    MTD.Sel=MTD.Sel/nsimu,
                                    MTD.Allo=MTD.Allo/No.Subject,
                                    Over.Sel=Over.Sel/nsimu,
                                    Over.Allo=Over.Allo/No.Subject,
                                    Risk.of.HT=Risk.of.HT/nsimu,
                                    PerDLT=No.DLT/No.Subject, 
                                    Duration=Duration/nsimu
      )
    }
    rownames(final.res) <- rownames(res.all.df)
    return(final.res)
  }
  
  ###############################################################################
  ############################MAIN DUNCTION######################################
  ###############################################################################  
  
  run.fn <- function(i){
    if (design == 'CFO' || design == 'aCFO'){
      res <- CFO.simu(target, p.true, ncohort, init.level, cohortsize, design, prior.para, seed = seeds[i],
                      cutoff.eli, extrasafe, offset)
    }else{
      res <- lateonset.simu(target, p.true, tau, cohortsize, ncohort, accrual, tite.dist, accrual.dist, 
                            design, init.level, prior.para=list(alp.prior=target, bet.prior=1-target), seed = seeds[i])
    }
    ress <- list(
      res=res,
      paras=list(p.true=p.true, 
                 mtd=tmtd, 
                 prior.para=prior.para,
                 target=target,
                 ncohort=ncohort,
                 cohortsize=cohortsize)
    )
    return(ress)
  }
  
  tmtd <- MTD.level(target, p.true)
  
  
  results <- lapply(1:nsimu, run.fn)
  results_nopara <- lapply(1:nsimu, function(i)results[[i]]$res)
  
  numTrials <- length(results_nopara)
  ndose <- length(results_nopara[[1]]$dose.ns)
  Perc <- rep(0, ndose)
  nPatients <- rep(0, ndose)
  nTox <- rep(0, ndose)
  tol.Subjs <- 0
  nonErrStops <- 0
  for (res in results_nopara){
    if (res$MTD != 99){
      nonErrStops <- nonErrStops + 1
      Perc[res$MTD] <- 1 + Perc[res$MTD]
    }
    nPatients <- nPatients + res$dose.ns
    nTox <- res$DLT.ns + nTox
    tol.Subjs <- tol.Subjs + sum(res$dose.ns)
  }
  Perc <- Perc/numTrials
  errStop <- numTrials-nonErrStops
  
  sy <- post.process(results)
  
  if (design == 'CFO' || design == 'aCFO'){
    out <- list(selPercent=Perc, dose.ns=nPatients/nsimu, DLT.ns=nTox/nsimu, p.true = p.true, 
                simu.oc = data.frame(MTDSel=sy$MTD.Sel, MTDAllo=sy$MTD.Allo, 
                                     overSel=sy$Over.Sel, overAllo=sy$Over.Allo, averDLT=sy$PerDLT,
                                     errStop=errStop, tol.Subjs=tol.Subjs),
                simu.setup = data.frame(target = target,ncohort = ncohort, 
                                        cohortsize = cohortsize, design = design, nsimu = nsimu))
  }else{
    out <- list(selPercent=Perc, dose.ns=nPatients/nsimu, DLT.ns=nTox/nsimu, p.true = p.true,
                simu.oc = data.frame(MTDSel=sy$MTD.Sel, MTDAllo=sy$MTD.Allo, overSel=sy$Over.Sel,
                                     overAllo=sy$Over.Allo, averDLT=sy$PerDLT, averDur = sy$Duration,
                                     errStop=errStop, tol.Subjs=tol.Subjs),
                simu.setup = data.frame(target = target, ncohort = ncohort, 
                                        cohortsize = cohortsize, design = design, nsimu = nsimu))
  }
  class(out) <- "cfo"
  return(out)
}
